name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Run Tests
        run: nosetests
